#!/bin/bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BATCH_DIR="$ROOT/BatchExperiments"
PYTHON="${PYTHON:-/people/dass304/.conda/envs/combopt/bin/python}"
CONDA_ENV_NAME="${CONDA_ENV_NAME:-combopt}"
JOB_PYTHON="${JOB_PYTHON:-/people/dass304/.conda/envs/combopt/bin/python}"

# Mirrors the 7 dataset list from run_dataset_area05_10seed.sh.
DATASETS=(
  "mobile_net_tosa"
  "rez_net_tosa"
  "squeeze_net_tosa"
  "anomaly_detection_tosa"
  "image_classification_tosa"
  "keyword_spotting_tosa"
  "visual_wake_words_tosa"
)

# Uses the full 10-seed sweep documented in run_dataset_area05_10seed.sh.
SEEDS=(42 43 44 45 46 47 48 49 50 51)

if [[ -n "${DATASETS_OVERRIDE:-}" ]]; then
  read -r -a DATASETS <<<"$DATASETS_OVERRIDE"
fi
if [[ -n "${SEEDS_OVERRIDE:-}" ]]; then
  read -r -a SEEDS <<<"$SEEDS_OVERRIDE"
fi

PROFILE="${PROFILE:-full}"
AREA="${AREA:-0.5}"
RESULT_TAG="${RESULT_TAG:-dataset_area05_10seed}"
RUN_TAG="${RUN_TAG:-$(date '+%Y%m%d-%H%M%S')}"
CONFIG_ROOT="${CONFIG_ROOT:-$ROOT/BatchExperiments/dataset_area05_configs}"
MANIFEST="${MANIFEST:-$CONFIG_ROOT/$PROFILE/graph_suite_area05/manifest.csv}"

MIP_SOLVER_TOOL="${MIP_SOLVER_TOOL:-cvxpy-scip}"
MIP_SOLVE_MODE="${MIP_SOLVE_MODE:-exact}"
MIP_SW_CONSTRAINT_MODE="${MIP_SW_CONSTRAINT_MODE:-pairwise_topo}"
MIP_USE_REDUCED_SW="${MIP_USE_REDUCED_SW:-false}"
MIP_ACCEPT_NONOPTIMAL="${MIP_ACCEPT_NONOPTIMAL:-false}"
MIP_VERBOSE="${MIP_VERBOSE:-true}"
MIP_TIME_LIMIT_SEC="${MIP_TIME_LIMIT_SEC:-3600}"
MIP_GAP="${MIP_GAP:-0}"
MIP_NODE_LIMIT="${MIP_NODE_LIMIT:-0}"
RUN_TIMEOUT_SEC="${RUN_TIMEOUT_SEC:-0}"
TIMEOUT_KILL_AFTER_SEC="${TIMEOUT_KILL_AFTER_SEC:-180}"

SBATCH_ACCOUNT="${SBATCH_ACCOUNT:-encode_optimize}"
SBATCH_PARTITION="${SBATCH_PARTITION:-slurm}"
SBATCH_NTASKS_PER_NODE="${SBATCH_NTASKS_PER_NODE:-1}"
SBATCH_CPUS_PER_TASK="${SBATCH_CPUS_PER_TASK:-1}"
SBATCH_MEM="${SBATCH_MEM:-64G}"
SBATCH_TIME="${SBATCH_TIME:-2:00:00}"
SBATCH_JOB_NAME="${SBATCH_JOB_NAME:-run_cvxpy_mip}"

SBATCH_ROOT="${SBATCH_ROOT:-$BATCH_DIR/slurm_jobs/run_mip_sid}"
SBATCH_OUT_ROOT="${SBATCH_OUT_ROOT:-$BATCH_DIR/slurm_outputs/run_mip_sid}"
SELECTION_ROOT="${SELECTION_ROOT:-$SBATCH_ROOT/selected_${RUN_TAG}}"
DRY_RUN="${DRY_RUN:-0}"

join_by_comma() {
  local IFS=', '
  echo "$*"
}

mkdir -p "$SBATCH_ROOT" "$SBATCH_OUT_ROOT" "$SELECTION_ROOT"

if [[ ! -f "$MANIFEST" ]]; then
  echo "Manifest not found: $MANIFEST"
  exit 1
fi

echo "Preparing MIP submissions"
echo "  Manifest     : $MANIFEST"
echo "  Area         : $AREA"
echo "  Datasets     : $(join_by_comma "${DATASETS[@]}")"
echo "  Seeds        : $(join_by_comma "${SEEDS[@]}")"
echo "  Run tag      : $RUN_TAG"
echo "  SBATCH root  : $SBATCH_ROOT"
echo "  Output logs  : $SBATCH_OUT_ROOT"
echo "  Conda env    : $CONDA_ENV_NAME"
echo "  Job python   : $JOB_PYTHON"
echo "  Dry run      : $DRY_RUN"

"$PYTHON" "$ROOT/tools/select_configs_from_manifest.py" \
  --manifest "$MANIFEST" \
  --out-dir "$SELECTION_ROOT" \
  --graph-names "${DATASETS[@]}" \
  --seeds "${SEEDS[@]}" \
  --areas "$AREA"

EXPECTED_CONFIGS=$(( ${#DATASETS[@]} * ${#SEEDS[@]} ))
ACTUAL_CONFIGS="$("$PYTHON" - <<'PY' "$SELECTION_ROOT/selected_manifest.csv"
from pathlib import Path
import sys
import pandas as pd

path = Path(sys.argv[1])
if not path.exists() or path.stat().st_size == 0:
    print(0)
else:
    print(len(pd.read_csv(path)))
PY
)"

if [[ "$ACTUAL_CONFIGS" -ne "$EXPECTED_CONFIGS" ]]; then
  echo "Config selection mismatch: expected $EXPECTED_CONFIGS rows, found $ACTUAL_CONFIGS in $SELECTION_ROOT/selected_manifest.csv"
  exit 1
fi

SUBMITTED=0

while IFS=$'\t' read -r CONFIG_PATH GRAPH_NAME SEED_VALUE; do
  [[ -n "$CONFIG_PATH" ]] || continue

  CONFIG_BASE="$(basename "$CONFIG_PATH" .yaml)"
  METHOD_DIR="$BATCH_DIR/dataset_area05/$GRAPH_NAME/mip"
  CSV_FRAGMENT_DIR="$METHOD_DIR/csv_fragments"
  RESULT_PREFIX="${RESULT_TAG}_${GRAPH_NAME}_mip"

  JOB_DIR="$SBATCH_ROOT/$GRAPH_NAME"
  LOG_DIR="$SBATCH_OUT_ROOT/$GRAPH_NAME"
  SBATCH_FILE="$JOB_DIR/${CONFIG_BASE}.sbatch"
  LOG_OUT="$LOG_DIR/${CONFIG_BASE}_%j.out"
  LOG_ERR="$LOG_DIR/${CONFIG_BASE}_%j.err"
  CSV_FRAGMENT="$CSV_FRAGMENT_DIR/${CONFIG_BASE}.csv"

  mkdir -p "$JOB_DIR" "$LOG_DIR" "$METHOD_DIR" "$METHOD_DIR/partitions" "$CSV_FRAGMENT_DIR"

  cat >"$SBATCH_FILE" <<EOF
#!/bin/bash
# Auto-generated by BatchExperiments/run_mip_sid.sh
# Mirrors the dataset/seed selection from BatchExperiments/run_dataset_area05_10seed.sh
# using the Slurm configuration from the "Original configuration (for rm or others)"
# branch in BatchExperiments/run_mip_rounak.sh.
# This job runs in the combopt conda environment and writes a per-config CSV fragment
# to avoid concurrent appends to one shared CSV.

#SBATCH --output=$LOG_OUT
#SBATCH --error=$LOG_ERR
#SBATCH -A $SBATCH_ACCOUNT
#SBATCH -p $SBATCH_PARTITION
#SBATCH --ntasks-per-node=$SBATCH_NTASKS_PER_NODE
#SBATCH --cpus-per-task=$SBATCH_CPUS_PER_TASK
#SBATCH --mem=$SBATCH_MEM
#SBATCH -t $SBATCH_TIME
#SBATCH --job-name=$SBATCH_JOB_NAME

set -euo pipefail

cd "$ROOT"
module load python/miniforge25.3.0
source /share/apps/python/miniforge25.3.0/etc/profile.d/conda.sh

mkdir -p "$METHOD_DIR" "$METHOD_DIR/partitions" "$CSV_FRAGMENT_DIR"

conda run -n "$CONDA_ENV_NAME" --no-capture-output env \
  CONFIG_GLOB="$CONFIG_PATH" \
  OUTDIR="$METHOD_DIR" \
  SOLVER_TOOL="$MIP_SOLVER_TOOL" \
  FAST_MIP="1" \
  MIP_SOLVE_MODE="$MIP_SOLVE_MODE" \
  MIP_SW_CONSTRAINT_MODE="$MIP_SW_CONSTRAINT_MODE" \
  MIP_USE_REDUCED_SW="$MIP_USE_REDUCED_SW" \
  MIP_ACCEPT_NONOPTIMAL="$MIP_ACCEPT_NONOPTIMAL" \
  MIP_VERBOSE="$MIP_VERBOSE" \
  MIP_TIME_LIMIT_SEC="$MIP_TIME_LIMIT_SEC" \
  MIP_GAP="$MIP_GAP" \
  MIP_NODE_LIMIT="$MIP_NODE_LIMIT" \
  RUN_TIMEOUT_SEC="$RUN_TIMEOUT_SEC" \
  TIMEOUT_KILL_AFTER_SEC="$TIMEOUT_KILL_AFTER_SEC" \
  HWSW_OUTPUT_DIR="$METHOD_DIR" \
  HWSW_SOLUTION_DIR="$METHOD_DIR/partitions" \
  HWSW_RESULT_PREFIX="$RESULT_PREFIX" \
  HWSW_RESULT_CSV="$CSV_FRAGMENT" \
  HWSW_RUN_TAG="$RUN_TAG" \
  PYTHON="$JOB_PYTHON" \
  bash -lc 'cd "'"$ROOT"'" && ./run_all_mip_configs.sh'
EOF

  chmod +x "$SBATCH_FILE"

  if [[ "$DRY_RUN" =~ ^(1|true|yes|on)$ ]]; then
    echo "DRY_RUN sbatch $SBATCH_FILE"
  else
    SUBMIT_OUTPUT="$(sbatch "$SBATCH_FILE")"
    echo "$SUBMIT_OUTPUT :: $GRAPH_NAME seed=$SEED_VALUE :: $CONFIG_BASE"
    SUBMITTED=$((SUBMITTED + 1))
  fi
done < <(
  "$PYTHON" - <<'PY' "$SELECTION_ROOT/selected_manifest.csv" "$ROOT"
from pathlib import Path
import csv
import sys

manifest = Path(sys.argv[1])
root = Path(sys.argv[2]).resolve()

with manifest.open(newline="") as handle:
    reader = csv.DictReader(handle)
    for row in reader:
        config_path = Path(row["config_path"])
        if not config_path.is_absolute():
            config_path = root / config_path
        print(f"{config_path}\t{row['graph_name']}\t{row['seed']}")
PY
)

if [[ "$DRY_RUN" =~ ^(1|true|yes|on)$ ]]; then
  echo "Prepared $ACTUAL_CONFIGS sbatch files under $SBATCH_ROOT"
else
  echo "Submitted $SUBMITTED jobs"
fi
