---
out_dir: results
metric_best: mae
num_workers: 4
dim_out: 1
wandb:
  use: True
  name: mc
  project: copt-maxclique-rb
  entity: guy-wolf
dataset:
  format: rb
  name: small
  task: graph
  # task_type: classification
  split_mode: cv-kfold-5
  split_dir: splits
  node_encoder: true
  node_encoder_name: GraphStats
  graph_stats: ['degree', 'cluster_coefficient', 'triangle_count']
  multiprocessing: true
  label: false
posenc_LapPE:
  enable: false
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 4
    skip_zero_freq: true
    eigvec_abs: true
  model: DeepSet
  dim_pe: 32
  layers: 2
  n_heads: 4  # Only used when `posenc.model: Transformer`
  raw_norm_type: none
posenc_RWSE:
  enable: false
  kernel:
    times_func: range(2,22)  # if no self-loop, then RWSE1 will be all zeros
  model: Linear
  dim_pe: 32
  raw_norm_type: BatchNorm
posenc_GraphStats:
  enable: true
  model: Linear
  dim_pe: 32
  raw_norm_type: none
posenc_NormalRE:
  enable: false
  dim_pe: 16
train:
  mode: copt
  # compile: True
  task: maxclique
  batch_size: 256
  val_period: 1
  ckpt_period: 100
  ckpt_best: true
  ckpt_monitor: size/valid
model:
  type: gnn
  loss_fun: maxclique_loss
  edge_decoding: dot
  graph_pooling: mean
gnn:
  head: copt_inductive_node
  layers_pre_mp: 4
  layers_mp: 8
  layers_post_mp: 1
  dim_inner: 128
  layer_type: gcnconv
  stage_type: skipsum
  batchnorm: true
  act: elu
  last_act: null
  last_norm: minmax
  dropout: 0.3
  agg: mean
  normalize_adj: false
  hybrid:
    activation_att1: elu
    activation_att2: elu
    activation: elu
  hybrid_v2:
    skip: true
optim:
  base_lr: 0.001
  max_epoch: 10
  optimizer: adamW
  weight_decay: 1e-5
  scheduler: cos
  num_warmup_epochs: 5
maxclique_loss:
  beta: 0.1
metrics:
  maxclique:
    dec_length: 300
    num_seeds: 10