---
out_dir: results
metric_best: acc
num_workers: 4
wandb:
  use: True
  name: sweep
  project: copt_graphgym
  entity: wenkelf
dataset:
  format: pc
  name: v100_40
  task: graph
  # task_type: classification
  split_mode: cv-kfold-5
  split_dir: splits
  node_encoder: False
  node_encoder_name: RWSE
  set_graph_stats: true
  graph_stats: ['degree', 'eccentricity', 'cluster_coefficient', 'triangle_count']
  multiprocessing: true
  label: false
posenc_LapPE:
  enable: true
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 4
    skip_zero_freq: true
    eigvec_abs: true
  model: DeepSet
  dim_pe: 32
  layers: 2
  n_heads: 4  # Only used when `posenc.model: Transformer`
  raw_norm_type: none
posenc_RWSE:
  enable: true
  kernel:
    times_func: range(2,22)  # if no self-loop, then RWSE1 will be all zeros
  model: Linear
  dim_pe: 32
  raw_norm_type: BatchNorm
posenc_GraphStats:
  enable: true
  model: Linear
  dim_pe: 32
  raw_norm_type: none
posenc_NormalRE:
  enable: true
  dim_pe: 16
train:
  mode: copt
  # compile: True
  task: plantedclique
  batch_size: 64
  eval_period: 1
  ckpt_period: 100
  ckpt_best: true
model:
  type: gnn
  loss_fun: plantedclique_loss
  edge_decoding: dot
  graph_pooling: mean
gnn:
  head: copt_graph
  layers_pre_mp: 1
  layers_mp: 2
  layers_post_mp: 1
  dim_inner: 256
  layer_type: hybrid
  stage_type: skipsum
  batchnorm: true
  act: relu
  last_act: null
  dropout: 0.3
  agg: mean
  normalize_adj: false
optim:
  base_lr: 0.003
  max_epoch: 200
  optimizer: adamW
  weight_decay: 1e-5
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5