# Graph and problem configuration
graph-file: "/people/mehr668/encode_scripts/hw_sw_partition_min_cut/soda-benchmark-graphs/pytorch-graphs/squeeze_net_tosa.dot"
area-constraint: 0.5
hw-scale-factor: 0.3
hw-scale-variance: 0.5
comm-scale-factor: 1.0
seed: 42
solution-dir: "partitions"

# Random assignment trials
random:
    num_samples: 50
    p: 0.5

# PSO Configuration
pso:
  c1: 0.575
  c2: 0.1
  w: 1.05
  n_particles: 500
  iterations: 2000
  verbose: True

# Discrete Binary PSO Configuration
dbpso:
  c1: 0.575
  c2: 0.1
  w: 1.05
  k: 4
  p: 2
  n_particles: 500
  iterations: 2000
  verbose: True

# Comprehensive Learning PSO Configuration
clpso:
  c: 1
  n_individuals: 500
  iterations: 2000

# Comprehensive Learning PSO Configuration
ccpso:
  c: 1
  n_individuals: 500
  iterations: 2000
  group_sizes: [5,10,20]

# Genetic GL25 configuration
gl25:
  iter: 20000
  n_pop: 500

shade:
  iter: 20000
  n_individuals: 500

jade:
    iter: 20000
    n_individuals: 500

esa:
    iter: 10000