graph-file: inputs/task_graph_topology/custom/paper_fig3_11node.dot
area-constraint: 0.5
hw-scale-factor: 1.0
hw-scale-variance: 0.1
comm-scale-factor: 1.0
seed: 42
solver-tool: cvxpy
solution-dir: outputs/fig3_partitions_swprio_compare
result-file-prefix: fig3_diffgnn_order_gnnprio
output-dir: outputs/swprio_compare
taskgraph-dir: inputs/task_graph_complete
taskgraph-pickle: inputs/task_graph_complete/taskgraph-paper_fig3_11node-instance-config-config_fig3_taskgraph_gnn.pkl
methods: diff_gnn_order
opt-cost-type: makespan
visualization:
  enabled: false
  include_input_graph: true
  include_output_schedule: true
  out_dir: outputs/final_visualizations/fig3_fast_simple
  input_dir: outputs/final_visualizations/fig3_fast_simple/input
  schedule_dir: outputs/final_visualizations/fig3_fast_simple/schedule
  strict_partitions: false
