#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import os
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Materialize a filtered config set from a manifest CSV.")
    parser.add_argument("--manifest", type=Path, required=True, help="Manifest CSV generated by the topology config tool.")
    parser.add_argument("--out-dir", type=Path, required=True, help="Directory where filtered config symlinks will be created.")
    parser.add_argument("--graph-names", nargs="*", default=None, help="Optional exact graph-name filter.")
    parser.add_argument("--seeds", nargs="*", type=int, default=None, help="Optional seed filter.")
    parser.add_argument("--areas", nargs="*", type=float, default=None, help="Optional area-constraint filter.")
    parser.add_argument("--max-nodes", type=int, default=0, help="Optional node-count ceiling. Non-positive disables it.")
    parser.add_argument("--max-configs", type=int, default=0, help="Optional cap on the number of selected configs.")
    parser.add_argument("--no-clean", action="store_true", help="Do not clean the output directory before materializing links.")
    return parser.parse_args()


def _safe_float(text: str | None) -> float | None:
    if text is None or text == "":
        return None
    try:
        return float(text)
    except Exception:
        return None


def _safe_int(text: str | None) -> int | None:
    if text is None or text == "":
        return None
    try:
        return int(float(text))
    except Exception:
        return None


def _selected_rows(args: argparse.Namespace) -> list[dict]:
    graph_filter = set(args.graph_names or [])
    seed_filter = set(args.seeds or [])
    area_filter = {round(float(v), 6) for v in (args.areas or [])}

    rows: list[dict] = []
    with args.manifest.open(newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            graph_name = row.get("graph_name", "")
            seed = _safe_int(row.get("seed"))
            area = _safe_float(row.get("area_constraint"))
            nodes = _safe_int(row.get("nodes"))

            if graph_filter and graph_name not in graph_filter:
                continue
            if seed_filter and seed not in seed_filter:
                continue
            if area_filter and (area is None or round(area, 6) not in area_filter):
                continue
            if args.max_nodes > 0 and (nodes is None or nodes > args.max_nodes):
                continue
            rows.append(row)

    rows.sort(
        key=lambda row: (
            _safe_int(row.get("nodes")) or 0,
            row.get("graph_name", ""),
            _safe_float(row.get("area_constraint")) or 0.0,
            _safe_int(row.get("seed")) or 0,
        )
    )
    if args.max_configs > 0:
        rows = rows[: args.max_configs]
    return rows


def _materialize(rows: list[dict], out_dir: Path, clean: bool) -> None:
    if clean and out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    selection_csv = out_dir / "selected_manifest.csv"
    if rows:
        with selection_csv.open("w", newline="") as handle:
            writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
            writer.writeheader()
            writer.writerows(rows)
    else:
        selection_csv.write_text("")

    for index, row in enumerate(rows, start=1):
        rel_config = Path(row["config_path"])
        src = rel_config if rel_config.is_absolute() else ROOT / rel_config
        link_name = f"{index:03d}__{src.name}"
        dst = out_dir / link_name
        if dst.exists() or dst.is_symlink():
            dst.unlink()
        os.symlink(src, dst)


def main() -> int:
    args = parse_args()
    rows = _selected_rows(args)
    _materialize(rows, args.out_dir, clean=not args.no_clean)
    print(f"Selected {len(rows)} configs into {args.out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
